### ISSUE TITLE
how to get wandb access?

### ISSUE THREAD

**Issue by dedoogong** [dunbar12138/DSNeRF#1]
hello ! thank u for ur great work. 
I would like to train your network with my custom data(around 100 images)
I set 
train_scene = [ 1,   2,   3,   4,   5,   6,   7,   8,   9, 
        11,  12,  13,  14,  15,  16,  17,  18,  19,  
        21,  22,  23,  24,  25,  26,  27,  28,  29,  
        31,  32,  33,  34,  35,  36,  37,  38,  39,  
        41,  42,  43,  44,  45,  46,  47,  48,  49, 
        51,  52,  53,  54,  55,  56,  57,  58,  59,  
        61,  62,  63,  64,  65,  66,  67,  68,  69,  
        71,  72,  73,  74,  75,  76,  77,  78,  79,
        81,  82,  83,  84,  85,  86,  87,  88,  89, 
        91,  92,  93,  94,  95,  96,  97,  98,  99, 
        101, 102, 103, 104, 105, 106, 107, 108, 109, 
        111, 112, 113, 114]
and then run the train code but it shows I need your accept for access.
I joined wandb and copied my API key but it doesn't work as below. 
```
wandb.errors.CommError: Permission denied, ask the project owner to grant you access
```
Please help me~!

**Comment by dunbar12138** [comment]
Could you use the latest code? Should be fine.
