### ISSUE TITLE
Standard rendering demo mentioned in the tutorial outputs corrupted images and video. 

### ISSUE THREAD

**Issue by saunair** [dunbar12138/DSNeRF#23]
*No code changes, just followed the readme*

I downloaded the pretrained model to the `./logs` folder, and initiated: 
```
run_nerf.py --config configs/fern_dsnerf.txt --render_only
```

I keep seeing a compression warning every iteration as follows: 
```
max: 5.9706993
Lossy conversion from float32 to uint8. Range [0.10505260527133942, 5.970699310302734]. Convert image to uint8 prior to saving to suppress this warning.
 99%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏   | 119/120 [14:05<00:07,  7.12s/it]119 7.150676250457764
max: 5.921188
Lossy conversion from float32 to uint8. Range [0.11592616140842438, 5.921187877655029]. Convert image to uint8 prior to saving to suppress this warning.
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 120/120 [14:12<00:00,  7.10s/it]
Done rendering ./logs/fern_dsnerf_2v/renderonly_path_000000
```

And the output mentioned above says the following: 
![000](https://user-images.githubusercontent.com/9517734/145890313-65bd903c-877e-4944-a6c6-92cc8d8aa478.png)

**Comment by dunbar12138** [comment]
Hi, thanks for your attention to our work!

This is because the experiment name in the `config/fern_dsnerf.txt` file doesn't match the pre-trained model name. So the result you saw was actually created by a new experiment with initialized weights. 

I have corrected the experiment name in the config file. You can either pull the repo or correct the name in `config/fern_dsnerf.txt` by yourself. Thanks for pointing that out for us!

**Comment by saunair** [comment]
Thank you so much! That might be it. 
I also had to set `shuffle=False` in the dataloaders, otherwise I was getting an exception at the generator in `run_nerf.py` at line  https://github.com/dunbar12138/DSNeRF/blob/main/run_nerf.py#L866

```RuntimeError: Expected a 'cuda' device type for generator but found 'cpu'```
