### ISSUE TITLE
I cannot run python imgs2poses.py data/fern_2view/images

### ISSUE THREAD

**Issue by pathanon** [dunbar12138/DSNeRF#27]
![problem_generate_point](https://user-images.githubusercontent.com/98586707/151528784-6a041291-f88d-4e03-8b86-bab7c6217844.JPG)

**Comment by aman190202** [comment]
How did you solve this out?

**Comment by vladhondru25** [comment]
The issue is that the path to colmap is hardcoded. Easiest fix is to change that path (or even remove the whole path "/home/jasonzh2/.local/bin/" if colmap is in your PATH)
