### ISSUE TITLE
Question about the regularization added to the loss

### ISSUE THREAD

**Issue by saunair** [dunbar12138/DSNeRF#29]
Hi Authors, 
I had a question about the implementation of the depth loss. 
The depth calculated in the [colmap depth loader ](https://github.com/dunbar12138/DSNeRF/blob/main/load_llff.py#L371) seems to be the `z` value of the point in camera frame, but the depth computed from the NeRF seems to be the [distance of the point along the ray's direction](https://github.com/dunbar12138/DSNeRF/blob/f30fafaa041019fa32a2a3a016e419c4fe72b39f/run_nerf_helpers.py#L377). 

What am I reading incorrectly here?

**Comment by dunbar12138** [comment]
Both the depths are the z value of the point. Check the get_rays functions [here](https://github.com/dunbar12138/DSNeRF/blob/f30fafaa041019fa32a2a3a016e419c4fe72b39f/run_nerf_helpers.py#L268). The ray directions are not given in unit length, but [x,y,-1] in the camera frame.

**Comment by saunair** [comment]
Thanks for the reply!
It indeed isn't unit length, but is built of the point `[i/focal_length, -j/ focal_length, -1]` which is equivalent to `[i, -j, -focal_length]`, right? 
That means the value of the summed z is in direction of the ray. Or did I miss something?

**Comment by dunbar12138** [comment]
Given this definition of ray direction `rd` and ray origin `ro`, if a point is specified by `p = ro + rd * z`, `z` should be the distance along z-axis

**Comment by saunair** [comment]
I get it now, my understanding of z-vals and the distances were incorrect in the integration function. Thanks for taking out the time to explain this!
