### ISSUE TITLE
Potential view inconsistency in depth loss

### ISSUE THREAD

**Issue by NagabhushanSN95** [dunbar12138/DSNeRF#31]
Hi,

I noticed that you compute depth in input views in https://github.com/dunbar12138/DSNeRF/blob/main/load_llff.py#L371 but the depth given by NeRF model is in cannonical view https://github.com/dunbar12138/DSNeRF/blob/main/run_nerf_helpers.py#L377

Shouldn't both the depths be brought to same view before computing depth loss? Please let me know if I missed something

**Comment by dunbar12138** [comment]
The transformation between different cameras is just rigid transformation, which conserves the length.

**Comment by NagabhushanSN95** [comment]
Oh okay. Thanks! Closing the issue
