### ISSUE TITLE
Confusion about the implementation of weight calculation for depth and RGB rendering

### ISSUE THREAD

**Issue by JerryX1110** [dunbar12138/DSNeRF#46]
Hi, thanks for your neat and excellent work! However, I am confused about the implementation of the weight for depth and RGB rendering. In the code implementation, it seems that the weight is calculated by the product of T(t) and alpha(t) (https://github.com/dunbar12138/DSNeRF/blob/168a13edd8a08396e3ad775283eeb65145317205/run_nerf_helpers.py#L374) while it is formulated as the product of T(t) and sigma(t) in the paper.

**Comment by dunbar12138** [comment]
Hi, thanks for your interest!

T(t)alpha(t) is an approximation of T(t)sigma(t)\delta t. You can refer to Eq 1 and 3 in the [NeRF paper](https://arxiv.org/pdf/2003.08934.pdf).

**Comment by JerryX1110** [comment]
Got that! Thanks~
