### ISSUE TITLE
Unreasobable result with the pre-trained model.

### ISSUE THREAD

**Issue by wutong16** [dunbar12138/DSNeRF#5]
Hi, thanks for your great work and code!

I'm trying to reproduce the demo results with the pre-trained model, but I got unreasonable frame outputs as below:
![image](https://user-images.githubusercontent.com/28827385/127154700-88ca0ade-baeb-4e44-9deb-26b67d155c90.png)

The checkpoint `fern_2v/020000.tar` was loaded. The only modification to the code is replacing `from torchsearchsorted import searchsorted` with`from torch import searchsorted` and the corresponding usage of it.
Do you have any idea what may have gone wrong here?

Thanks in advance!

**Comment by dunbar12138** [comment]
You might be using incompatible versions of data and checkpoints. Could you try again with most updated data and checkpoints? I don't see this issue with them.

**Comment by wutong16** [comment]
It's working alright now, thanks!
