### ISSUE TITLE
The value range of depth loss

### ISSUE THREAD

**Issue by iYuqinL** [dunbar12138/DSNeRF#57]
Hello, I try to run your code with my own data, but I found the depth loss is pretty large (0.25).
I'm not sure if it is because the generated depth is not right in my own data, so I want to know the depth loss's value in your training.

**Comment by dunbar12138** [comment]
Should be smaller than 0.01 after training.

**Comment by iYuqinL** [comment]
thank you for your reply, I do make a mistake.
