### ISSUE TITLE
Potential error in llff data loading weights/reprojection_error

### ISSUE THREAD

**Issue by NagabhushanSN95** [dunbar12138/DSNeRF#59]
In your [updated code](https://github.com/dunbar12138/DSNeRF/blob/main/run_nerf.py#L838), you are reading the reprojection error. But the [dataloader](https://github.com/dunbar12138/DSNeRF/blob/main/load_llff.py#L434) is not updated for the same.

**Comment by dunbar12138** [comment]
Thanks for pointing that out! You can use the dataset [here](https://drive.google.com/file/d/1RjhfcbsywOvw0ts1AFSri91mKANvEVOa/view?usp=sharing)
