### ISSUE TITLE
Does no_ndc=True give better results than no_ndc=False

### ISSUE THREAD

**Issue by NagabhushanSN95** [dunbar12138/DSNeRF#60]
Hi,

NeRF recommends setting no_ndc=False for forward-facing scenes. But in your configs, you have suggested setting no_ndc=True. Why?

**Comment by dunbar12138** [comment]
Thanks for your interest!

So far we only have depth supervision in the non-ndc space.

**Comment by Wanggcong** [comment]
> non-ndc space

Hi, have you tried ndc space for depth supervision? How to transform colmap depth into ndc depth, and what are the results?
