### ISSUE TITLE
how to generate sparse 3d points given known cameras 

### ISSUE THREAD

**Issue by Wanggcong** [dunbar12138/DSNeRF#64]
Hi, thank you for the work.

I have a question about the sparse 3d points given known cameras. I have read  [this issue](https://github.com/dunbar12138/DSNeRF/issues/20) and [this issue](https://github.com/dunbar12138/DSNeRF/issues/28#issue-1120505855).

I also carefully read [this link of colmap](https://colmap.github.io/faq.html#reconstruct-sparse-dense-model-from-known-camera-poses). There are multiple steps, like image.txt, cameras.txt, and point3D.txt. I would like to know how to prepare these to align your work to better reproduction for comparison.

I think this is the way (with known camera poses) you prepare NeRF real (LLFF) and DTU since we need unified poses for training and test images. The steps are as follows:

(1) estimate poses with training and test images (because we need a unified coordinate for training and test).
(2) With camera poses of training images, we generate sparse 3d points. Note, we cannot access test images to generate sparse 3d points.

In the code, the paper only provides code for `python imgs2poses.py <your_scenedir>`

It would be better if a script like `python imgs2poses.py <your_scenedir>  <your camera poses>  <your camera intrinsics>` is provided.  I would like to know how to prepare these to align your work to better reproduction for comparison.

Thank you.

**Comment by dunbar12138** [comment]
Hi, thanks for your suggestion!

We provide the test poses aligned with training poses in the LLFF dataset [here](https://drive.google.com/file/d/1RjhfcbsywOvw0ts1AFSri91mKANvEVOa/view?usp=sharing). Let me know if that's still not enough for reproduction or comparison.

For the DTU dataset, we're also considering releasing our pre-processed data with the depth information.

Thanks for your suggestion about updating the script. We'll also consider making it if possible.
