### ISSUE TITLE
Question about ray distance t and depth D

### ISSUE THREAD

**Issue by xiechun-tsukuba** [dunbar12138/DSNeRF#70]
Hi,

Thank you for the great work.

If my understanding is correct, the depth _D_ of a 3D point is its Z value in a camera's local coordinate system. It is different from the ray distance _t_, which is the distance from the point to the camera center. In fact, _D = sin(θ) × t_, where θ is the angle between the camera plane and the ray. Therefore, even in an ideal case, the distribution of _h(t)_ and _D_ are not expected to be the same. 

However, in section 3.2, I see you minimizing the KL divergence between these two distributions. Wouldn't that cause some problems? Or did I miss something?

I am new to nerf, please forgive me if the answer is trivial.

Thank you

**Comment by dunbar12138** [comment]
Please check the issue [here](https://github.com/dunbar12138/DSNeRF/issues/29).

**Comment by xiechun-tsukuba** [comment]
Thank you!
