### ISSUE TITLE
Unable to reproduce the fern_2v result

### ISSUE THREAD

**Issue by qiwen98** [dunbar12138/DSNeRF#73]
Hi, thank you for your great work.

I use 

```
python run_nerf.py --config configs/fern_2v.txt --render_only" 
```

command with the pretrained model, it gave me these results

https://user-images.githubusercontent.com/45889437/202093543-8c02a2f1-8989-48d7-8ff5-ead60cdbdf36.mp4

https://user-images.githubusercontent.com/45889437/202093571-40752187-6e50-4847-912f-cbdd1ac6dbe9.mp4

while when I re-trained the model from scratch with this command 

```
python run_nerf.py --config configs/fern_2v.txt --weighted_loss 
```

and render it with my trained model, it gave this following results

https://user-images.githubusercontent.com/45889437/202093604-a700141a-77a3-4e85-a25d-b842d8cf902e.mp4

https://user-images.githubusercontent.com/45889437/202094729-efc05d95-0c5c-4d06-8b8a-1505e3b295b4.mp4

Do you have any clue ? Is the sigma-loss necessary in order to reproduce the same quality with the given-pretrained model? Thanks

**Comment by dunbar12138** [comment]
Interesting. Seems the camera trajectory is off. Did you use the provided dataset?

**Comment by qiwen98** [comment]
> Interesting. Seems the camera trajectory is off. Did you use the provided dataset?

Hi, I am able to reproduce the result now, there was some mistake in my code setting, tq very much :)
