### ISSUE TITLE
Why calculate the weights twice

### ISSUE THREAD

**Issue by Trent-tangtao** [dunbar12138/DSNeRF#75]
Hi, thanks for your great work!
I have the question about why to recalculate [weights](https://github.com/dunbar12138/DSNeRF/blob/d9deb70ac1464348aebbe5e32fc98aeca1920f70/loss.py#L84) when calculating sigma_loss. While we already have the weights in the forward [here](https://github.com/dunbar12138/DSNeRF/blob/d9deb70ac1464348aebbe5e32fc98aeca1920f70/run_nerf_helpers.py#L377).

**Comment by dunbar12138** [comment]
Hi, thanks for your interest!

This is because we might want to sample different points and also different numbers of points when calculating the loss.

**Comment by Trent-tangtao** [comment]
ok, thanks!
