### ISSUE TITLE
Cannot reproduce performance on forn_2v 

### ISSUE THREAD

**Issue by AliceMegatron** [dunbar12138/DSNeRF#80]
Hi~ Thank you very much for the open source code and paper

I tried to train a model with default config，but I got poor performance on forn_2v.I strictly followed the instructions to start the reproduction experiment，However, my experimental results are quite different from the released results；
result of mine：
![000](https://user-images.githubusercontent.com/36946556/206118903-dd71808c-2e44-4281-a99a-3bcd93f2163d.png)
![002](https://user-images.githubusercontent.com/36946556/206118977-211638b0-80fd-41e4-b103-963b748f68a6.png)
![007](https://user-images.githubusercontent.com/36946556/206119001-0e148d0b-af7e-4635-beb2-bb4896953283.png)
log of last iter：
![image](https://user-images.githubusercontent.com/36946556/206119122-21b5ba67-f292-4d6c-81dd-9bc5724dcb5d.png)

Am i missing something ?  Really appreciate for your help.

**Comment by dunbar12138** [comment]
Hi,

A test PSNR of ~19 is expected on the horns data. I would suggest several things to check:

- Are the latest code and data being used?
- Are some parameters being changed? (e.g., number of sampled rays to fit into memory)
- Check the released pre-trained model and see whether the results are similar.

Thanks for your interest!
